### ISSUE TITLE
Byte-string keys no longer work

### ISSUE THREAD

**Issue by codders** [pywbem/nocasedict#139]
### Actual behavior

Creating a NocaseDict with byte-string keys generates an error since #122 was merged (version 1.0.5):

```
from nocasedict import NocaseDict
NocaseDict([(b'MyKey', b'myValue')])

>>> AttributeError: 'bytes' object has no attribute 'casefold'
```

### Expected behavior

Byte-string keys worked fine in versions 1.0.4 and lower due to use of `.lower()` (which exists on both byte-strings and unicode strings). Either the SemVer should be bumped, and the API changed to generate an error for byte-string keys, or a compatibility wrapper should be added.

### Execution environment

* nocasedict version: 1.1.0
* Python version: 3.11
* Operating System (type+version): Linux

**Comment by andy-maier** [comment]
Sounds like a valid issue. I'll look into it.

**Comment by andy-maier** [comment]
I fixed this by falling back to `lower()` if `casefold()` does not exist. Will be released as 1.1.1 and in 2.0.0

Note that you can also override `NocaseDict.__casefold__()` in case you need any more special case insensitivity behavior.

**Comment by codders** [comment]
Awesome - thank you! :)
